#!/bin/tcsh
#
# take a RTKLIB *.pos solution file and split
# it into 2 files, 1 containing just header info
# and 1 containing just solution/processed data
#
# INPUT:
#
# *.pos           RTK kinematic solution file outputted by RTKLIB
#
# OUTPUT:
#
# *.hdr          solution file containing only the header from input pos file
# *.prd          solution file containing only positions from input pos file
#
# Originally written by tschuh-at-princeton.edu, 12/28/2021
# Last modified by tschuh-at-princeton.edu, 02/03/2022

set infile = $1

set hdrend = `awk '/%  GPST/ {print NR; exit}' $infile`

# create hdr and prd files from original file
awk 'NR<='"$hdrend"' {print}' $infile >! $infile:r.hdr
awk 'NR>'"$hdrend"' {print}' $infile >! $infile:r.prd
